export const keywordCategoryMap = [
  {
    keywords: [
      'accounting',
      'finance',
      'auditor',
      'cpa',
      'financial',
      'controller',
    ],
    category: 'Accounting and Finance',
  },
  {
    keywords: [
      'administration',
      'office',
      'admin',
      'secretary',
      'clerk',
      'assistant',
      'executive assistant',
    ],
    category: 'Administration and Office Support',
  },
  {
    keywords: [
      'advertising',
      'marketing',
      'brand',
      'seo',
      'content',
      'digital marketing',
      'ad',
      'social media manager',
      'account executive',
    ],
    category: 'Advertising and Marketing',
  },
  {
    keywords: [
      'architecture',
      'engineer',
      'engineering',
      'civil',
      'mechanical',
      'structural',
      'architect',
      'project engineer',
    ],
    category: 'Architecture and Engineering',
  },
  {
    keywords: [
      'art',
      'fashion',
      'design',
      'creative',
      'designer',
      'illustrator',
      'product designer',
    ],
    category: 'Art, Fashion, and Design',
  },
  {
    keywords: [
      'business',
      'operations',
      'management',
      'manager',
      'business operations',
      'strategy',
      'operations manager',
    ],
    category: 'Business Operations and Management',
  },
  {
    keywords: [
      'consulting',
      'project management',
      'consultant',
      'project manager',
      'pm',
      'implementation manager',
    ],
    category: 'Consulting and Project Management',
  },
  {
    keywords: [
      'customer service',
      'support',
      'customer support',
      'helpdesk',
      'client service',
      'csr',
      'client success manager',
    ],
    category: 'Customer Service and Support',
  },
  {
    keywords: [
      'data',
      'science',
      'analytics',
      'data scientist',
      'analyst',
      'big data',
    ],
    category: 'Data Science and Analytics',
  },
  {
    keywords: [
      'education',
      'training',
      'teacher',
      'instructor',
      'educator',
      'trainer',
      'coach',
    ],
    category: 'Education and Training',
  },
  {
    keywords: [
      'environmental',
      'agriculture',
      'sustainability',
      'farming',
      'conservation',
      'ecology',
      'regulatory affairs',
      'compliance',
    ],
    category: 'Environmental and Agriculture',
  },
  {
    keywords: [
      'health',
      'wellness',
      'fitness',
      'nutrition',
      'healthcare',
      'dietitian',
      'coach',
      'medical',
    ],
    category: 'Health and Wellness',
  },
  {
    keywords: [
      'hospitality',
      'tourism',
      'hotel',
      'restaurant',
      'travel',
      'guest service',
    ],
    category: 'Hospitality and Tourism',
  },
  {
    keywords: [
      'human resources',
      'hr',
      'recruitment',
      'talent',
      'people operations',
    ],
    category: 'Human Resources',
  },
  {
    keywords: [
      'information technology',
      'it',
      'computer science',
      'tech',
      'networking',
      'system admin',
      'devops',
      'software',
      'software engineer',
      'lead software engineer',
    ],
    category: 'Information Technology and Computer Science',
  },
  {
    keywords: [
      'legal',
      'lawyer',
      'attorney',
      'paralegal',
      'legal assistant',
      'litigation',
      'vice president legal',
    ],
    category: 'Legal',
  },
  {
    keywords: [
      'logistics',
      'transportation',
      'supply chain',
      'shipping',
      'warehouse',
      'delivery',
    ],
    category: 'Logistics and Transportation',
  },
  {
    keywords: [
      'manufacturing',
      'production',
      'factory',
      'assembly',
      'plant',
      'manufacture',
    ],
    category: 'Manufacturing and Production',
  },
  {
    keywords: [
      'media',
      'communication',
      'journalism',
      'public relations',
      'pr',
      'reporter',
    ],
    category: 'Media and Communication',
  },
  {
    keywords: [
      'military',
      'government',
      'defense',
      'public service',
      'armed forces',
    ],
    category: 'Military and Government',
  },
  {
    keywords: [
      'nonprofit',
      'social services',
      'ngo',
      'charity',
      'community',
      'volunteer',
    ],
    category: 'Nonprofit and Social Services',
  },
  {
    keywords: [
      'nursing',
      'healthcare',
      'nurse',
      'patient care',
      'medical',
      'clinical',
    ],
    category: 'Nursing and Healthcare',
  },
  {
    keywords: [
      'photography',
      'video',
      'animation',
      'videographer',
      'editor',
      'photographer',
    ],
    category: 'Photography, Video, and Animation',
  },
  {
    keywords: [
      'real estate',
      'property management',
      'realtor',
      'broker',
      'property',
    ],
    category: 'Real Estate and Property Management',
  },
  {
    keywords: [
      'retail',
      'consumer goods',
      'sales associate',
      'store manager',
      'retail sales',
    ],
    category: 'Retail and Consumer Goods',
  },
  {
    keywords: [
      'sales',
      'marketing',
      'account executive',
      'sales manager',
      'sales rep',
      'sales director',
    ],
    category: 'Sales and Marketing',
  },
  {
    keywords: [
      'science',
      'research',
      'scientist',
      'researcher',
      'lab',
      'laboratory',
    ],
    category: 'Science and Research',
  },
  {
    keywords: [
      'social media',
      'marketing',
      'social media manager',
      'content creator',
      'influencer',
    ],
    category: 'Social Media and Marketing',
  },
  {
    keywords: [
      'software',
      'development',
      'developer',
      'engineer',
      'programmer',
      'coder',
      'lead software engineer',
    ],
    category: 'Software Development',
  },
  {
    keywords: [
      'sports',
      'entertainment',
      'athlete',
      'coach',
      'trainer',
      'event manager',
    ],
    category: 'Sports and Entertainment',
  },
  {
    keywords: [
      'technical writing',
      'translation',
      'writer',
      'editor',
      'translator',
    ],
    category: 'Technical Writing and Translation',
  },
  {
    keywords: [
      'telecommunications',
      'networking',
      'telecom',
      'network engineer',
      'network admin',
    ],
    category: 'Telecommunications and Networking',
  },
  {
    keywords: [
      'travel',
      'hospitality',
      'tourism',
      'agent',
      'travel consultant',
    ],
    category: 'Travel and Hospitality',
  },
  {
    keywords: [
      'web development',
      'mobile development',
      'frontend',
      'backend',
      'fullstack',
      'developer',
    ],
    category: 'Web and Mobile Development',
  },
];
