export const openApplicationKeywords = [
  // English
  'spontaneous application',
  'open application',
  'unsolicited application',
  'speculative application',
  'general application',
  'submit your resume',
  'send us your cv',
  'expression of interest',
  'future opportunities',
  'join our talent pool',
  'join our team',
  'talent pool',
  'join us anytime',
  'open positions',
  'your dream job',
  'opportunities anytime',
  "If you don't see the role you're looking for...",
  "If you don't see the role you're looking for...",
  'see the role',

  // French
  'candidature spontanée',
  'demande spontanée',
  'candidature ouverte',
  'postulez spontanément',
  'rejoignez notre équipe',
  'rejoignez-nous',
  'envoyez votre cv',
  'soumettre votre cv',
  'postuler à tout moment',
  'opportunités futures',
  'postes ouverts',

  // German
  'initiativbewerbung',
  'offene bewerbung',
  'spekulative bewerbung',
  'unaufgeforderte bewerbung',
  'allgemeine bewerbung',
  'ihre bewerbung',
  'senden sie uns ihren lebenslauf',
  'zukünftige möglichkeiten',
  'bewerben sie sich jederzeit',
  'beitreten sie unserem team',

  // Spanish
  'solicitud espontánea',
  'aplicación abierta',
  'aplicación espontánea',
  'solicitud general',
  'envíanos tu cv',
  'exprésate',
  'oportunidades futuras',
  'envía tu cv',
  'únete a nuestro equipo',
  'postulación abierta',
  'únete a nuestro talento',

  // Italian
  'candidatura spontanea',
  'domanda spontanea',
  'candidatura aperta',
  'invia il tuo cv',
  'unisciti al nostro team',
  'opportunità future',
  'unisciti a noi',
  'posizioni aperte',

  // Dutch
  'open sollicitatie',
  'spontane sollicitatie',
  'algemene sollicitatie',
  'initiatiefsollicitatie',
  'open posities',
  'toekomstige vacatures',
  'stuur ons jouw cv',
  'sluit aan bij ons team',

  // Portuguese
  'candidatura espontânea',
  'aplicação aberta',
  'solicitação espontânea',
  'envie seu currículo',
  'oportunidades futuras',
  'junte-se à nossa equipe',
  'envie seu cv',
  'candidatura geral',
];
